# fly.toml file generated for star-network on 2023-03-06T09:54:59-07:00

app = "star-network"
kill_signal = "SIGTERM"
kill_timeout = 30

[build]
  [build.args]
    BUNDLER_VERSION = "2.4.7"
    NODE_VERSION = "19.7.0"
    RUBY_VERSION = "3.2.1"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "8080"
  RAILS_LOG_TO_STDOUT = "YES"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  app = "bin/rails server"
  worker = "bin/bundle exec sidekiq"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  tcp_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = "30s"
    method = "get"
    path = "/healthz/all.json"
    protocol = "http"
    restart_limit = 3
    timeout = "5s"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
