name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://starnetwork.space
    env:
      DOCKER_BUILDKIT: 1
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.157.0
        with:
          bundler-cache: true
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: ./bin/rails fly:deploy
